
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - "3000:3000"
